/** Core MVP flow routes */
export const ROUTES = {
  INSTRUMENT: "instrument",
  TRACK_CHOICE: "track-choice",
  LIBRARY: "library",
  UPLOAD: "upload",
  REVIEW: "review",
  PRACTICE: "practice",
  SHEET_EDITOR: "sheet-editor",
};

export const BACK_ROUTE = {
  [ROUTES.INSTRUMENT]: null,
  [ROUTES.TRACK_CHOICE]: ROUTES.INSTRUMENT,
  [ROUTES.LIBRARY]: ROUTES.TRACK_CHOICE,
  [ROUTES.UPLOAD]: ROUTES.TRACK_CHOICE,
  [ROUTES.REVIEW]: ROUTES.TRACK_CHOICE,
  [ROUTES.PRACTICE]: ROUTES.REVIEW,
  [ROUTES.SHEET_EDITOR]: ROUTES.PRACTICE,
};
